[package]
name = "rustcast"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.27.2"
eframe = "0.27.2"
egui_extras = "0.27.2"
env_logger = "0.11.3"
log = "0.4.22"
rodio = { version = "0.17.3", features = ["symphonia-all"], default-features = false }
ureq = "2.9.7"
